name: Deploy Spring Boot Application to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-app:latest

  deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    needs: build

    steps:
      - name: Add SSH Key to Agent
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > tkadprokey.pem
          chmod 600 tkadprokey.pem
          eval "$(ssh-agent -s)"
          ssh-add tkadprokey.pem

      - name: Deploy Application via SSH
        run: |
          ssh -i tkadprokey.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-app:latest
            docker stop spring-boot-app || true
            docker rm spring-boot-app || true
            docker run -d --name spring-boot-app \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e DB_URL=${{ secrets.DB_URL }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-app:latest
          EOF
          